language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
- nightly
- hhvm-3.3
- hhvm-3.6

matrix:
    allow_failures:
        - php: hhvm-3.3
        - php: hhvm-3.6
        - php: nightly

services:
  - mongodb
  - redis-server

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:*"
  - composer install
  - php vendor/codeception/codeception/codecept build

before_script:
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script: php vendor/codeception/codeception/codecept run