language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
- nightly
- hhvm-3.3
- hhvm-3.6

matrix:
  allow_failures:
    - php: hhvm-3.3
    - php: hhvm-3.6
    - php: nightly

services:
  - mongodb
  - redis-server
  - mysql
  - postgresql

before_install:
  - mysql -e "CREATE DATABASE travis_test;"
  - mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'test';"
  - mysql -e "GRANT ALL ON travis_test.* TO 'travis'@'localhost';"
  - psql -c "CREATE DATABASE travis_test;" -U postgres
  - psql -c "CREATE USER travis WITH password 'test';" -U postgres
  - psql -c "GRANT ALL privileges ON DATABASE travis_test TO travis;" -U postgres
  - pecl install -f mongodb-1.2.0
  - pecl install -f redis-3.0.0
  - mongo travis_test --eval 'db.addUser("travis", "test");'

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:*"
  - composer install
  - php vendor/codeception/codeception/codecept build

script: php vendor/codeception/codeception/codecept run