language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
- nightly
- hhvm
- hhvm-3.3
- hhvm-3.6
- hhvm-3.9
- hhvm-3.12
- hhvm-nightly
install:
    - composer self-update
    - composer global require "fxp/composer-asset-plugin:*"
    - composer install
    - php vendor/codeception/codeception/codecept build
script: php vendor/codeception/codeception/codecept run