language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
- nightly
- hhvm-3.3
- hhvm-3.6

matrix:
  allow_failures:
    - php: hhvm-3.3
    - php: hhvm-3.6
    - php: nightly

services:
  - mongodb
  - redis-server
  - mysql
  - postgresql

before_install:
  - mysql -u root -e "CREATE DATABASE travis_test;"
  - psql -c "CREATE DATABASE travis_test;" -U postgres
  - pecl install -f mongodb-1.2.0
  - pecl install -f redis-3.0.0
  - mongo travis_test --eval 'db.addUser("travis", "test");'

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:*"
  - composer install
  - vendor/bin/codecept build

script: vendor/bin/codecept run --coverage --coverage-xml

after_success:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 306795868d2bec06339d9638c013d15c4d9b3404d013ad88d6a72185f584f8ad